import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy policy", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <section className="legal-page section-pad"><p className="eyebrow">Legal</p><h1>Privacy policy</h1><p className="legal-updated">Last updated: 22 September 2026</p><div className="legal-copy"><h2>Information we collect</h2><p>When you contact {siteConfig.legalName}, we may receive the details you choose to provide, including your name, email address, country and information about the accounting services you are asking about.</p><h2>How we use it</h2><p>We use enquiry information to respond to you, understand the services you may need, manage our relationship with you and meet legal or professional obligations that apply to our work.</p><h2>Sharing information</h2><p>We do not sell personal information. Contact-form information is transmitted through service providers used to operate the website and deliver enquiries. Information may also be shared with professional advisers where this is necessary to deliver agreed services or comply with law.</p><h2>International work</h2><p>Because we support international clients, information may sometimes need to be handled across borders. Where this applies, appropriate legal and security safeguards should be used.</p><h2>Retention and security</h2><p>We keep personal information only for as long as it is reasonably needed for the purpose it was collected, contractual requirements, record keeping or applicable law.</p><h2>Your rights</h2><p>Depending on the law that applies to you, you may have rights to access, correct, delete, restrict or object to the use of your personal information. You can contact us through the <Link href="/contact">contact form</Link>.</p></div></section>;
}
