import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = { title: "Website terms", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <section className="legal-page section-pad"><p className="eyebrow">Legal</p><h1>Website terms</h1><p className="legal-updated">Last updated: 25 September 2026</p><div className="legal-copy"><h2>Company details</h2><p>{siteConfig.legalName}, trading as Shiel Accountants, operates this website at {siteConfig.url}. Our core client markets are Ireland, the UK and Gibraltar. Services in other jurisdictions are accepted selectively and may require local professional input.</p><h2>General information</h2><p>The content on this website is general information about {siteConfig.legalName} and its services. It is not accounting, tax, legal, investment or other professional advice for any particular person or situation.</p><h2>No adviser-client relationship</h2><p>Using the website or sending an enquiry does not by itself create a professional engagement. Any work will be subject to an agreed scope and, where applicable, engagement terms.</p><h2>Accuracy</h2><p>We aim to keep website information clear and current, but laws, rates and administrative practice can change. You should obtain advice based on your facts before acting on technical information.</p><h2>Third parties</h2><p>Where the website links to third-party services or information, those resources are controlled by their respective providers.</p><h2>Governing law</h2><p>These website terms are governed by the laws of Ireland. The courts of Ireland will have jurisdiction, except where mandatory consumer or other applicable law gives you the right to bring a claim elsewhere.</p><h2>Contact</h2><p>Questions about these website terms can be sent through the <Link href="/contact">contact form</Link>.</p></div></section>;
}
